pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'us-east-1'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/YOUR_USERNAME/event-driven-pipeline.git'
            }
        }

        stage('Terraform Init') {
            steps {
                sh 'cd Code/terraform && terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh 'cd Code/terraform && terraform plan'
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'cd Code/terraform && terraform apply -auto-approve'
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }
        failure {
            echo 'Deployment Failed!'
        }
    }
}
